### ISSUE TITLE
Configuration - Badges

### ISSUE THREAD

**Issue by noiwid** [teamRibcage/YuniFi#1]
Hi,
It's really a nice theme! I'm struggling to reach a dashboard like yours, do you mind to share your Lovelace config file?
Thanks in advance for your feedback.

**Comment by teamRibcage** [comment]
Thanks @noiwid , I'm glad you like it! 🙂
The config file is quite lengthy (6,979 lines altogether). Is there a particular part I can help you out with?

**Comment by noiwid** [comment]
Hi @teamRibcage,
Many thanks for your fast feedback!

The first line (where you show family members, and their status: home/office) is one of the items that I don't know how to build. But the whole config would be so helpful 😅  It can be shared easily with pastebin.com for ex.

**Comment by teamRibcage** [comment]
The ‘Badges’, as well as the majority of the rest of my page(s), rely heavily on the Custom:Button-Card (linked in the README). By defining the `styles:` of the buttons, their size and background (or lack thereof) can be made to appear exactly the way you’d like them to:

```yaml
styles:
  card:
    - background-color: rgb(0,0,0,0)
    - box-shadow: 0px 0px 0px 0px
    - padding: 0px 0px 0px 0px
    - height: 80px
  icon:
    - color: var(--base-colors-seagreen)
    - padding: 0px 0px 0px 0px
    - width: 40px
```

I use these icons (and different `styles` based on entity `state`) to indicate system status, and whether or not updates or issues exist related to the various server components:

[Showing HACS update available]
![system_status_badges](https://user-images.githubusercontent.com/76419115/144542298-91f4daf4-2abf-4abc-973a-60d72ad8f9e9.png)
```yaml
state:
  - value: 0
    styles:
      icon:
        - color: var(--base-colors-seagreen)
        - padding: 0px 0px 0px 0px
        - width: 40px
      card:
        - box-shadow: 0px 0px 0px 0px
        - padding: 0px 0px 0px 0px
styles:
  card:
    - background-color: rgb(0,0,0,0)
    - box-shadow: 0px 0px 0px 1px var(--base-colors-red)
    - padding: 0px 0px 0px 0px
    - height: 80px
  icon:
    - color: var(--base-colors-red)
    - padding: 0px 0px 0px 0px
    - width: 40px
```
Likewise, by defining the button’s `icon` (or `entity_picture`, again based on entity `state`) as one of a few custom .png icons I made, I have a friendly way to update family’s locations as a ‘Badge’ at the top of each page as well:

[Showing Matt is home, Heather is not at home]
<img src="https://user-images.githubusercontent.com/76419115/144541257-f913601a-d3f0-4d4f-9c44-464ea7b6bd1e.png" alt="Family Location Badges" width="350">
```yaml
state:
  - value: home
    entity_picture: /local/icons/heather_home.png
  - value: not_home
    entity_picture: /local/icons/earth.png
styles:
  card:
    - height: 80px
    - padding: 0px 0px 0px 0px
    - background-color: rgb(0,0,0,0)
    - box-shadow: 0px 0px 0px 0px
    - padding: 0px 0px 0px 0px
  entity_picture:
    - height: 65px
    - width: 65px
    - padding: 0px 0px 0px 0px
```

By defining the button's `name` and/or `label` based on entity `state`, the family member's name and changes to location can also be displayed with text. Spacing is again controlled using blank buttons in a ‘Horizontal Stack'.

Hope that helps @noiwid! 🙂
